export const planetOptions = [
  "Cristall South",
  "Cristall North",
  "Crutha South",
  "Crutha North",
  "Gredica South",
  "Gredica North",
  "Kita South",
  "Kita North",
  "Lusa South",
  "Lusa North",
  "Minas South",
  "Minas North",
  "Ozara South",
  "Ozara North",
  "Pampas South",
  "Pampas North",
  "Sindari South",
  "Sindari North",
  "Zando South",
  "Zando North",
];

export const inhabitantOptions = [
  "Cristallian F",
  "Cristallian M",
  "Cruthan F",
  "Cruthan M",
  "Gredican F",
  "Gredican M",
  "Kitan F",
  "Kitan M",
  "Lusan F",
  "Lusan M",
  "Minasan F",
  "Minasan M",
  "Ozaran F",
  "Ozaran M",
  "Pampan F",
  "Pampan M",
  "Sindarin F",
  "Sindarin M",
  "Zandoan F",
  "Zandoan M",
];

export const objectOptions = [
  "Ancient Lusan Trident",
  "Battle Axe",
  "Battle Shovel",
  "Cristallian Bow",
  "Cristallian Ray Gun",
  "Cristallian Staff",
  "Cristallian Sword",
  "Cruthan Blaster",
  "Cruthan Death Mace",
  "Sindarin Flame Thrower",
  "Golden Hammer",
  "Gredican Power Staff",
  "Gredican Sword",
  "Ice Cleaver",
  "Kitan Ice Bow",
  "Kitan Ice Staff",
  "Kitan Ice Sword",
  "Lusan Water Saber",
  "Lusan Water Staff",
  "Lusan Xtreme Soaker",
  "Minasan Bow",
  "Minasan Ore Staff",
  "Minasan Ore Sword",
  "Ozaran Blaster",
  "Ozaran Bone Axe",
  "Ozaran Death Saber",
  "Ozaran Sand Staff",
  "Pampan Grass Staff",
  "Pampan Grass Sword",
  "Phoenix Rising",
  "Quartz Ray Gun",
  "Royal Ozaran Bow",
  "Sindarin Fire Bow",
  "Sindarin Fire Saber",
  "Sindarin Fire Staff",
  "SST Fishing Pole",
  "Sword of Zando",
  "The Eternal Torch",
  "Staff of Zando",
  "Zandoan Vine Bow",
];