export { LandingPage } from "./LandingPage"
export { NftGallery } from "./NftGallery"
export { NftView } from "./NftView"
export { HowItWorks } from "./HowItWorks"
export { TheStory } from "./TheStory"
export { NotFound } from "./NotFound"
